### ISSUE TITLE
graph.flm with functional covariate and contrasts=TRUE fails with error

### ISSUE THREAD

**Issue by jmhrrsn** [myllym/GET#4]
Hi again,

I get a strange error message from the following example:

```R
library('GET')
library('fda.usc')

Y <- fdata(matrix(rnorm(96 * 120), 120, 96))
Z <- fdata(matrix(rnorm(96 * 120), 120, 96))
data <- data.frame(V=as.factor(runif(120) > 0.5))
result <- graph.flm(50,
                    Y ~ V + Z,
                    Y ~ Z,
                    factors=data,
                    contrasts=TRUE,
                    curve_sets=list(Y=Y, Z=Z))
```
The error I get (with GET 0.1-8) is 
```
Error in (function (Y, dfs, formula.full, nameinteresting, ...) : 
The option 'contrasts' only valid for discrete factors with at least two levels.
...
```
but as you can see from the formula, the variable of interest is a discrete factor with 2 levels 🙂

I think this might be a bug? I wasn't able to find anything in the documentation that suggests that this is disallowed.

Thanks!

**Comment by myllym** [comment]
Thank you for this bug detection! The problem occurred in the case where some of the covariates/factors are given in the curve_sets (meaning that their value depends on the argument r (argvals) of the functions) and some in `factors.` In this case, also the factors given in `factors` are replicated for each r. This was done with matrix, after which a factor was no longer a factor. I changed this now to do this instead using `rep` and `dims`, and I hope it now works as it should. The bug has now been fixed in the github version of GET, and will appear in the next update to CRAN then.
